benawad/dogehouse

- kofta/src/vscode-webview/pages/Login.tsx
https://youtu.be/2m9nUP-e8Co?t=485
[![image](https://user-images.githubusercontent.com/193136/107810225-eb9b0e80-6d9e-11eb-878b-c2c2a32b28c8.png)](https://youtu.be/2m9nUP-e8Co?t=485)
> Whoa, lowercase h.

- kofta/src/vscode-webview/pages/RoomPage.tsx
> feat: show usercount inside room

- kofta/public/manifest.json
**Do I really create a pull request for this?**
Spoiler alert: Yeah I did.
Added the app as a PWA on my android phone. At startup the app displays the nice doge logo but the title underneath still was "Create React App Sample". So yeah, I changed it and create a PR for it. Keep up the good work Ben :)
> Changed the PWA title

- kofta/src/vscode-webview/components/UserProfile.tsx
> feat: clickable username link to github

- kofta/src/vscode-webview/pages/RoomPage.tsx
Fixed showing total **requesting to speak** user
> fix total request count

- kofta/src/vscode-webview/components/Wrapper.tsx
> Fix button overlap on card

- kofta/src/vscode-webview/modules/room-chat/RoomChatInput.tsx
Fix the 0 space chat bug where people could use the zero space character to spam chat.
> Fix 0 space chat bug

- kofta/src/vscode-webview/components/BottomVoiceControl.tsx
Users are prompted to make sure they want to leave. No breaking changes.
> Feat: Confirm to leave 

- CODE_OF_CONDUCT.md
Hi, I added a code of conduct for new contributors. I personally do think it will help keep contributions clean. 
Hope that helps
> Added the CODE_OF_CONDUCT.md in root for new contributors

- kofta/.eslintrc.js
- kofta/package.json
- kofta/src/vscode-webview/Routes.tsx
- kofta/src/vscode-webview/atoms.ts
- kofta/src/vscode-webview/components/KeybindListener.tsx
- kofta/src/vscode-webview/components/ProfileButton.tsx
- kofta/src/vscode-webview/components/UserNode.tsx
- kofta/src/vscode-webview/components/UserProfile.tsx
- kofta/src/vscode-webview/components/keyboard-shortcuts/MuteKeybind.tsx
- kofta/src/vscode-webview/components/keyboard-shortcuts/PTTKeybind.tsx
- kofta/src/vscode-webview/pages/InviteList.tsx
- kofta/src/vscode-webview/pages/SearchUsersPage.tsx
moved _eslingConfig_ from `package.json` to `.eslintrc.js` and fix eslint warnings
before            |  after
:-------------------------:|:-------------------------:
> fix: eslint warnings

- README.md
used https://shields.io/ badge generator, can add other badges on demand...
> ReadME badge init

- kofta/src/vscode-webview/Router.tsx
- kofta/src/vscode-webview/Routes.tsx
- kofta/src/vscode-webview/pages/NotFoundPage.tsx
Resolves [#147](https://github.com/benawad/dogehouse/issues/147)
> Added 404 page

- kofta/src/css/vscode.css
Default scrollbars before this PR:
Awesome scrollbars after this PR:
> Added styling for better scrollbars

- README.md
I added the discord badge to the readme to show that dogehouse has a discord server
> Discord badge for the README

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Hi, Added a Contributing file to help new contributors to doghouse
PS: Did some little modification in the Code of conduct file so contributors can reach out as well on the discord server.
> Added CONTRIBUTING.md in the root to guide and help new contributors

- kofta/src/vscode-webview/components/RoomCard.css
- kofta/src/vscode-webview/components/RoomCard.tsx
I'm not exactly sure how I'm supposed to add styles with pseudo-classes using the `style` prop, so I just made a CSS file next to RoomCard.tsx; hope you don't mind
> Add down and hover colors to RoomCard

- kofta/src/css/vscode.css
> Added background colour to option

- kofta/src/vscode-webview/pages/MyProfilePage.tsx
Matches arrow spacing:
https://github.com/benawad/dogehouse/blob/b47dcbb31fb9571a86c6d0dd22693921dd03a82c/kofta/src/vscode-webview/components/Backbar.tsx#L24-L33
Before:
After:
> Fix ProfilePage button spacing

- kofta/src/css/vscode.css
- kofta/src/vscode-webview/pages/Login.tsx
- Added [Ɖoge Symbol](https://www.google.com/search?q=doge+symbol)
- Improved the scrollbar interaction by adding hover and active states, which is much more consistent
> added Ɖoge symbol on the home page

- kousa/lib/business-logic/room_chat_logic.ex
BE validation for https://github.com/benawad/dogehouse/pull/232 
- Validates links using elixir URI.
- Validates message length to be less than or equal to 512.
> add BE link, mention, and message length validation

- CONTRIBUTING.md
1. Add recommended branch name
2. Change `master` to `staging` since it's not a thing anymore
> Fix PR recommendations

- kibbeh/.eslintrc.json
- kibbeh/.gitignore
- kibbeh/.stylelintrc.json
- kibbeh/next-env.d.ts
- kibbeh/next.config.js
- kibbeh/package-lock.json
- kibbeh/package.json
- kibbeh/pages/404.tsx
- kibbeh/pages/_app.js
- kibbeh/pages/_document.js
- kibbeh/pages/_error.js
- kibbeh/pages/index.tsx
- kibbeh/postcss.config.js
- kibbeh/styles/globals.css
- kibbeh/tailwind.config.js
- kibbeh/tsconfig.json
I also added my nice eslint and stylelint configs since we're starting from scratch
> Setup kibbeh

- kibbeh/src/stories/MinimizedRoomCard.story.tsx
- kibbeh/src/ui/BoxedIcon.tsx
- kibbeh/src/ui/Button.tsx
- kibbeh/src/ui/MinimizedRoomCard.tsx
I'm not sure if that "inverse action flow" is how I was supposed to do the mute, deafen and leave buttons, but I tried.
> Implement MinimizedRoomCard

- kebab/.gitignore
- kebab/README.md
- kebab/examples/chat/README.md
- kebab/examples/chat/package-lock.json
- kebab/examples/chat/package.json
- kebab/examples/chat/src/index.js
- kebab/package-lock.json
- kebab/package.json
- kebab/src/entities.ts
- kebab/src/index.ts
- kebab/src/raw.ts
- kebab/src/wrapper.ts
- kebab/tsconfig.json
Kebab is a new, rewritten API client that is going to be used in kibbeh.
> New folder: kebab!

- kofta/src/app/components/BlockedFromRoomUsers.tsx
- kofta/src/app/components/UserNode.tsx
- kofta/src/app/components/UserProfile.tsx
- kofta/src/app/modules/room-chat/RoomChatList.tsx
- kofta/src/app/pages/FollowListPage.tsx
- kofta/src/app/pages/FollowingOnlineList.tsx
Ben had approved this (privately)
> Show all usernames in monospace (kofta)

- kebab/README.md
- kebab/examples/chat/package.json
- kebab/examples/chat/src/index.ts
- kebab/examples/chat/tsconfig.json
- kebab/examples/chat/yarn.lock
- kebab/examples/mediasoup-audio/README.md
- kebab/examples/mediasoup-audio/src/index.ts
- kebab/examples/mediasoup-audio/yarn.lock
- kebab/examples/react-chat/README.md
- kebab/examples/react-chat/src/App.tsx
- kebab/examples/react-chat/yarn.lock
- kebab/package.json
- kebab/src/audio/index.ts
- kebab/src/audio/interface.ts
- kebab/src/audio/mediasoup-client.ts
- kebab/src/index.ts
- Better READMEs
- Cleaned up the examples
- Fixed a couple of audio related bugs and warnings
- Add the currently played user ID to consumer player parameters
Mic producing is still broken; don't merge if you need it
> More stuff in kebab

- kebab/src/ast.ts
- kebab/src/entities.ts
- kebab/src/raw.ts
- kebab/src/wrapper.ts
No breaking changes and no big additions. I'm waiting for @goldyydev's PR to be accepted so I can add the `wrtc` package and start implementing audio for Node
> Polishing kebab

- kibbeh/src/modules/landing-page/LoginPage.tsx
- kibbeh/src/styles/globals.css
that `:not()` selector is fucked up
> Fix alternative logo position on the login page

- commitlint.config.js
- kebab/examples/bot/src/index.ts
- kebab/package.json
- kebab/src/http/bot.ts
- kebab/src/http/index.ts
- kebab/src/http/raw.ts
- kebab/src/index.ts
- kebab/src/responses.ts
- yarn.lock
conventional commits are weird
> Add POST /bot/auth to kebab

- kebab/package.json
- kebab/tsconfig.json
> Fix kebab for those who get it as a package

- kebab/README.md
- kebab/examples/bot/package-lock.json
- kebab/examples/bot/src/index.ts
- kebab/package.json
- kebab/src/README.md
- kebab/src/client/README.md
- kebab/src/client/http/bot.ts
- kebab/src/client/http/dev.ts
- kebab/src/client/http/endpoint.ts
- kebab/src/client/http/index.ts
- kebab/src/client/index.ts
- kebab/src/client/requester/auth.ts
- kebab/src/client/requester/chat.ts
- kebab/src/client/requester/index.ts
- kebab/src/client/requester/misc.ts
- kebab/src/client/requester/room.ts
- kebab/src/client/requester/user.ts
- kebab/src/client/subscriber/index.ts
- kebab/src/client/subscriber/legacy.ts
- kebab/src/client/type-util.ts
- kebab/src/entities.ts
- kebab/src/index.ts
- kebab/src/pagination.ts
- kebab/src/websocket/raw.ts
- kibbeh/src/modules/room/BlockedFromRoomUsers.tsx
- Audio stuff didn't get refactored because it still uses the old request format
- Kept the old wrapper because kibbeh uses it
- Only made one example use it because ummm
> New rewritten client for kebab
